import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { ToastContainer, Slide } from "@/components/ReactToast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navbar />
				{children}
				<ToastContainer
					position="top-right"
					autoClose={5000}
					hideProgressBar={false}
					closeOnClick
					rtl={false}
					transition={Slide}
					pauseOnFocusLoss
					draggable
					pauseOnHover
					theme="dark"
					toastStyle={{ backgroundColor: "#151A23" }}
				/>
			</body>
		</html>
	);
}
