// Generated by https://quicktype.io
import { User } from "./post";

export interface Comment {
	_id: string;
	user: User;
	text: string;
	parentComment?: string,
	createdAt: string;
	updatedAt: string;
}
