// Generated by https://quicktype.io

export interface Post {
    _id:     string;
    title:   string;
    content: string;
    picture: string;
    user:    User;
    likes:   number;
    createdAt: Date,
    updatedAt: Date
}

export interface User {
    _id:         string;
    username: string;
    photoUrl:    string;
}

