// Generated by https://quicktype.io

export interface User {
    username?:   string;
    email:       string;
    password:    string;
    displayName: string;
    photoUrl:    string;
    _id:         string;
}
